baseURL = "https://springfieldpres.org"
languageCode = "en-us"
title = "First Presbyterian Church of Springfield"
theme = "alpha-church"

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-168224170-1"

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "#"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "#"
    weight = 1

  [[menu.main]]
    name = "Pastor"
    parent = "About"
    url = "#"
    weight = 2

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Sermons"
    url = "#"
    parent = "Resources"
    weight = 1

  [[menu.main]]
    name = "Videos"
    url = "#"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "#cta"
    weight = 4

# Paramaters for the whole site
[params]
  title = "First Presbyterian Church of Springfield"
  subtitle = "The Heart of Christ in the Heart of Springfield"
  author = "Pastor Rosanna"
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "NRSV" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

  customCSS = ["example.css"]

  [params.banner]
    image = "img/banner.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.podcast]
    title = "Listen to First Presbyterian"
    subtitle = ""
    summary = "First Presbyterian sermons, talks, messages—podcasted."
    email = "rosanna@pastorrosanna.net"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "36.5092119"
    longitude = "-86.8863873"
    zoom = "15"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "XXXXXXXX"
    #language = "fr" #Optional
    #region = "FR" #Optional

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or else users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""


    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/First-Presbyterian-Church-Springfield-TN-437288392974522/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "/sermons/index.xml"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
